VACUUM ANALYZE Addirional_table;
VACUUM ANALYZE Amenity;
VACUUM ANALYZE Calendar;
VACUUM ANALYZE Geolocation;
VACUUM ANALYZE Host;
VACUUM ANALYZE Host_copy;
VACUUM ANALYZE Listing;
VACUUM ANALYZE Listing_copy;
VACUUM ANALYZE Listing_summary;
VACUUM ANALYZE Location;
VACUUM ANALYZE Neighbourhood;
VACUUM ANALYZE Price;
VACUUM ANALYZE Price_copy;
VACUUM ANALYZE Review;
VACUUM ANALYZE Review_summary;
VACUUM ANALYZE Room;
set enable_seqscan = off;